### ISSUE TITLE
Suggestion (?)

### ISSUE THREAD

**Issue by jpete4** [ezackr/BookBae#1]
https://github.com/ezackr/BookBae/blob/610ed20366a55f6c2725fe04816e879046299e06/database/CREATETABLES.sql#L51

if the login data has the hash and salt, does it need to store the password at all?

**Comment by jpete4** [comment]
also now I'm thinking of it I think there might be a better data type for hash and salt then 'TEXT'. They should be fixed size - IDK if text is the appropriate datatype for that though.

**Comment by Eado51415** [comment]
There's definitely a better data type than TEXT. I'll come up with some options! 
Also just removed password from the login_info table
