### ISSUE TITLE
API development for beta

### ISSUE THREAD

**Issue by jpete4** [ezackr/BookBae#9]

**Comment by jpete4** [comment]
I'd like to see tests added and a last review to ensure that the readme matched with each resource and they all match each other, but I think we should target merging this tonight

**Comment by jpete4** [comment]
https://github.com/ezackr/BookBae/blob/9-api-development-for-beta/backend/src/main/java/com/bookbae/server/CreateAccount.java#L24
I think we want to remove phone from this?

**Comment by Eado51415** [comment]
Yeah we do

**Comment by Eado51415** [comment]
Just made phone number optional and removed it from that line
